all:
  children:
    develop_ubuntu:
      hosts:
        test-develop-ubuntu:
          ansible_connection: community.general.incus
          ansible_incus_remote: local
          ansible_incus_project: default
          ansible_user: romira
