---
galaxy_info:
  author: romira
  description: Install and configure PostgreSQL
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - database
    - postgresql

dependencies: []
