$ANSIBLE_VAULT;1.1;AES256
63373664393464386633336533316336616330373534363339663362343833613039636130306661
3965623339643962666239363735343938386137613636610a326365656531653238366135353938
36376134326630663939616632643638363461653262663666356461623066323563323335343139
3137643766613830380a653762656661643737333635356365343832376633636366643335653561
33636236373630613733666463303333636461636335626430653930636131366239656138633232
38326361666538616338323165396135633164323365393030636238623164333865653863333235
38353639393031356531373539313736353835616637323137356262626532303061363966653762
63326333633365626534656430616136336237333764343835356131616235633135656461656664
39386334346139386637613065663262633261343132363432353336363137666264356230303166
64653865613330333061653939313766653139633565646331386139386337366330623861633239
39336362356165653237336562396562353835666431363131316130343161393662396430346466
62323831393736386331663162323630636437303630336630303461663161656565653138313830
38353466346164663135386266653930616232383037363530623930343831316639326130303032
64643338656363353939363135333730333039306331343334666531353632653264333133663261
30366633336235333234336261373334643133346466643738666135306432623066643835626537
31353138336233613262653538393262316134653635613236396136623264363535613135353562
34363831396539323038633862313233326333383437373039356636316239653631623534316637
62376238376134393636393135613331613839323863313036366432323066626233336137636261
306133396539663638663963353631326264
