---
# handlers file for docker

- name: Restart docker
  ansible.builtin.systemd:
    name: docker.service
    state: restarted
    daemon_reload: true
  become: true

- name: Reload docker
  ansible.builtin.systemd:
    name: docker.service
    state: reloaded
    daemon_reload: true
  become: true
