---
# tasks file for roles/bitwarden
- name: Gather facts
  ansible.builtin.gather_facts:
  when: ansible_facts.system is not defined
  tags:
    - bitwarden

- name: Import unix bitwarden tasks
  ansible.builtin.import_tasks:
    file: unix_bitwarden.yml
  when: ansible_facts.system in ['Linux', 'Darwin']

- name: Import windows bitwarden tasks
  ansible.builtin.import_tasks:
    file: win_bitwarden.yml
  when: ansible_facts.system in ['Win32NT']
