$ANSIBLE_VAULT;1.1;AES256
30376533633435343932303166373435326534373834323831663033366464316163383665316165
6631323937313064363832616230636233383964393332320a636163623963303338346636316162
33626238313164316236373733373133373837636161373531346131613333303464366639333335
6165653763343731360a303232366235383762643463396130303636626333323631303939623431
63373136613164626137383939366435616132316161356437376563653461313462616636316137
62333431373639653964643231323966353965333733303431616464363137313333353463623834
61353835626137333937616266656462326365616163353539336539373763316233653261626666
66306366653238363532663831343662653335646261366435343863666561623063323466346161
66313536393038316334383939333866343137396164663264396130383063386662373035633132
32356432643639353233353465666231396261363334393165316638316537346232633132333464
66663662363539336364386138363730373665643532653631303936336366626134383833663664
36333230646265373835373034393966306564643433643031366538343764343731626339633130
31386239656539376535616430316163623566623331653238303264366432386135626332356463
34643438363435353439326665306261396633313534633433613530333137656430366661666431
61353962376336646333336162353537376462333837633732343334306135623132623266376634
38316361376339643461646666323337366165396663613433343861356538346232386532616535
32653263626263356437343162666365633064653432633831656637316233653536366130326533
37396438343836663362656361336562333136346530383430303830643865356437396132636333
64353837346366306566623335353862346432346333663732653937316239396662333466373564
34396165306261376436
